//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sakuno.KanColle.Amatsukaze.Game.Models.MasterData
{
    public partial class ShipInfo : Calculated<IRawShipInfo>
    {
        internal ShipInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawShipInfo raw) => UpdateCore(raw);
        partial void UpdateCore(IRawShipInfo raw);
    }
    public partial class ShipTypeInfo : Calculated<IRawShipTypeInfo>
    {
        internal ShipTypeInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawShipTypeInfo raw) => UpdateCore(raw);
        partial void UpdateCore(IRawShipTypeInfo raw);
    }
    public partial class EquipmentTypeInfo : Calculated<IRawEquipmentTypeInfo>
    {
        internal EquipmentTypeInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawEquipmentTypeInfo raw) => UpdateCore(raw);
        partial void UpdateCore(IRawEquipmentTypeInfo raw);
    }
    public partial class EquipmentInfo : Calculated<IRawEquipmentInfo>
    {
        internal EquipmentInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawEquipmentInfo raw) => UpdateCore(raw);
        partial void UpdateCore(IRawEquipmentInfo raw);
    }
    public partial class MapAreaInfo : Calculated<IRawMapArea>
    {
        internal MapAreaInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawMapArea raw) => UpdateCore(raw);
        partial void UpdateCore(IRawMapArea raw);
    }
    public partial class MapInfo : Calculated<IRawMapInfo>
    {
        internal MapInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawMapInfo raw) => UpdateCore(raw);
        partial void UpdateCore(IRawMapInfo raw);
    }
    public partial class ExpeditionInfo : Calculated<IRawExpeditionInfo>
    {
        internal ExpeditionInfo(int id, ITableProvider owner) : base(id, owner) { }

        public override void Update(IRawExpeditionInfo raw) => UpdateCore(raw);
        partial void UpdateCore(IRawExpeditionInfo raw);
    }
}
