<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ReactiveUI.WPF" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(BasePath)src\Shell\Sakuno.ING.Shell.Hosting\Sakuno.ING.Shell.Hosting.csproj" />
    </ItemGroup>

</Project>
