<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InjectioName>ViewModels</InjectioName>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="InjectioName" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Injectio" />
        <PackageReference Include="ReactiveUI" />
        <PackageReference Include="Splat" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(BasePath)src\Game\Sakuno.ING.Game\Sakuno.ING.Game.csproj" />
    </ItemGroup>

</Project>
