//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;

namespace Sakuno.ING.Game.Models.Quests
{
    public sealed partial class Quest : BindableObject, IComparable<Quest>, IUpdatable<QuestId, RawQuest>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly PropertyChangedEventArgs __eventArgs_name = new PropertyChangedEventArgs(nameof(Name));
        [EditorBrowsable(EditorBrowsableState.Never)]
        private string _name;
        public string Name
        {
            get => _name;
            private set => Set(ref _name, value, __eventArgs_name);
        }

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly PropertyChangedEventArgs __eventArgs_state = new PropertyChangedEventArgs(nameof(State));
        [EditorBrowsable(EditorBrowsableState.Never)]
        private QuestState _state;
        public QuestState State
        {
            get => _state;
            private set => Set(ref _state, value, __eventArgs_state);
        }

        public int CompareTo(Quest other) => Id.CompareTo(other?.Id ?? default);

        public QuestId Id { get; }
        private readonly QuestManager _owner;

        public Quest(QuestId id, QuestManager owner)
        {
            Id = id;
            _owner = owner;
            CreateCore();
        }

        public Quest(RawQuest raw, QuestManager owner) : this(raw.Id, owner) => Update(raw);

        partial void CreateCore();

        public void Update(RawQuest raw)
        {
            Name = raw.Name;
            State = raw.State;

            UpdateCore(raw);
        }

        [GeneratedCode("Game objects generator", "")]
        partial void UpdateCore(RawQuest raw);

        public override string ToString() => $"Quest {Id}";
    }

}
