// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sakuno.ING.Game.Logger;

namespace Sakuno.ING.Game.Logger.Migrations
{
    [DbContext(typeof(LoggerContext))]
    [Migration("20180527085104_Expedition")]
    partial class Expedition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029");

            modelBuilder.Entity("Sakuno.ING.Game.Logger.Entities.EquipmentCreation", b =>
                {
                    b.Property<long>("TimeStamp");

                    b.Property<int>("AdmiralLevel");

                    b.Property<int>("EquipmentCreated");

                    b.Property<bool>("IsSuccess");

                    b.Property<int>("Secretary");

                    b.Property<int>("SecretaryLevel");

                    b.HasKey("TimeStamp");

                    b.ToTable("EquipmentCreationTable");
                });

            modelBuilder.Entity("Sakuno.ING.Game.Logger.Entities.ExpeditionCompletion", b =>
                {
                    b.Property<long>("TimeStamp");

                    b.Property<int>("ExpeditionId");

                    b.Property<string>("ExpeditionName");

                    b.Property<int>("Result");

                    b.HasKey("TimeStamp");

                    b.ToTable("ExpeditionCompletionTable");
                });

            modelBuilder.Entity("Sakuno.ING.Game.Logger.Entities.ShipCreation", b =>
                {
                    b.Property<long>("TimeStamp");

                    b.Property<int>("AdmiralLevel");

                    b.Property<int>("EmptyDockCount");

                    b.Property<bool>("IsLSC");

                    b.Property<int>("Secretary");

                    b.Property<int>("SecretaryLevel");

                    b.Property<int>("ShipBuilt");

                    b.HasKey("TimeStamp");

                    b.ToTable("ShipCreationTable");
                });

            modelBuilder.Entity("Sakuno.ING.Game.Logger.Entities.EquipmentCreation", b =>
                {
                    b.OwnsOne("Sakuno.ING.Game.Logger.Entities.MaterialsEntity", "Consumption", b1 =>
                        {
                            b1.Property<long>("EquipmentCreationTimeStamp");

                            b1.Property<int>("Bauxite");

                            b1.Property<int>("Bullet");

                            b1.Property<int>("Fuel");

                            b1.Property<int>("Steel");

                            b1.ToTable("EquipmentCreationTable");

                            b1.HasOne("Sakuno.ING.Game.Logger.Entities.EquipmentCreation")
                                .WithOne("Consumption")
                                .HasForeignKey("Sakuno.ING.Game.Logger.Entities.MaterialsEntity", "EquipmentCreationTimeStamp")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Sakuno.ING.Game.Logger.Entities.ExpeditionCompletion", b =>
                {
                    b.OwnsOne("Sakuno.ING.Game.Logger.Entities.ItemRecordEntity", "RewardItem1", b1 =>
                        {
                            b1.Property<long>("ExpeditionCompletionTimeStamp");

                            b1.Property<int>("Count");

                            b1.Property<int>("ItemId");

                            b1.ToTable("ExpeditionCompletionTable");

                            b1.HasOne("Sakuno.ING.Game.Logger.Entities.ExpeditionCompletion")
                                .WithOne("RewardItem1")
                                .HasForeignKey("Sakuno.ING.Game.Logger.Entities.ItemRecordEntity", "ExpeditionCompletionTimeStamp")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Sakuno.ING.Game.Logger.Entities.ItemRecordEntity", "RewardItem2", b1 =>
                        {
                            b1.Property<long>("ExpeditionCompletionTimeStamp");

                            b1.Property<int>("Count");

                            b1.Property<int>("ItemId");

                            b1.ToTable("ExpeditionCompletionTable");

                            b1.HasOne("Sakuno.ING.Game.Logger.Entities.ExpeditionCompletion")
                                .WithOne("RewardItem2")
                                .HasForeignKey("Sakuno.ING.Game.Logger.Entities.ItemRecordEntity", "ExpeditionCompletionTimeStamp")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Sakuno.ING.Game.Logger.Entities.MaterialsEntity", "MaterialsAcquired", b1 =>
                        {
                            b1.Property<long>("ExpeditionCompletionTimeStamp");

                            b1.Property<int>("Bauxite");

                            b1.Property<int>("Bullet");

                            b1.Property<int>("Fuel");

                            b1.Property<int>("Steel");

                            b1.ToTable("ExpeditionCompletionTable");

                            b1.HasOne("Sakuno.ING.Game.Logger.Entities.ExpeditionCompletion")
                                .WithOne("MaterialsAcquired")
                                .HasForeignKey("Sakuno.ING.Game.Logger.Entities.MaterialsEntity", "ExpeditionCompletionTimeStamp")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Sakuno.ING.Game.Logger.Entities.ShipCreation", b =>
                {
                    b.OwnsOne("Sakuno.ING.Game.Logger.Entities.MaterialsEntity", "Consumption", b1 =>
                        {
                            b1.Property<long>("ShipCreationTimeStamp");

                            b1.Property<int>("Bauxite");

                            b1.Property<int>("Bullet");

                            b1.Property<int>("Development");

                            b1.Property<int>("Fuel");

                            b1.Property<int>("Steel");

                            b1.ToTable("ShipCreationTable");

                            b1.HasOne("Sakuno.ING.Game.Logger.Entities.ShipCreation")
                                .WithOne("Consumption")
                                .HasForeignKey("Sakuno.ING.Game.Logger.Entities.MaterialsEntity", "ShipCreationTimeStamp")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
