name: build and test

on:
  push:
    branches: [master]
    paths:
    - '**.cs'
    - '**.csproj'
    - 'Directory.Build.*'
    - 'Directory.Packages.props'
    - '**.jsondesc'
    - '**.modeldesc'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'
        cache: true

    - name: Install dependencies
      run: dotnet restore --locked-mode

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
